In [1]:
import numpy as np

### Membuat Numpy Array

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
# python list
a = [1,2,3,4]
b = [5,6,7,8]
type(a), type(b)

(list, list)

In [6]:
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
arrayA = np.array(a)
arrayB = np.array(b)
type(arrayA), type(arrayB)

(numpy.ndarray, numpy.ndarray)

In [8]:
arrayA + arrayB

array([ 6,  8, 10, 12])

In [10]:
arrayA + arrayB
arrayA / arrayB

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [11]:
arrayA * 10 #broadcasting

array([10, 20, 30, 40])

In [12]:
y_pred = np.array([1,0,0,1,1,0,1,1])
labels = np.array([0,1,0,1,1,0,1,1])

mse = (1/len(labels)) * np.sum(np.square(y_pred - labels))
print(mse)

0.25


### Membuat Numpy Array 0 Dimensi (0D)

In [13]:
arr = np.array(42)

In [14]:
print(arr)

42


### Membuat Numpy Array 0 Dimensi (1D)

In [16]:
arr = np.array([1,2,3,4,5])

In [17]:
print(arr)

[1 2 3 4 5]


### Membuat Numpy Array 0 Dimensi (2D)

In [19]:
arr = np.array([[1,2,3],[4,5,6]])

In [20]:
print(arr)

[[1 2 3]
 [4 5 6]]


### Membuat Numpy Array 0 Dimensi (3D)

In [21]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [22]:
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Membuat Numpy Array 0s dan 1s

In [23]:
arr = np.zeros(5)

In [24]:
print(arr)

[0. 0. 0. 0. 0.]


In [25]:
arr = np.zeros((5,2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [26]:
arr = np.ones((7,7))

In [27]:
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [28]:
arr = np.ones((3,4,2))

In [29]:
print(arr)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


### Mengakses Elemen Pada Numpy Array 1D

In [33]:
arr = np.array([1,2,3,4])

In [34]:
arr[1:-1]

array([2, 3])

### Mengakses Elemen Pada Numpy Array 2D

In [35]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [36]:
print(arr[1,4])

10


In [37]:
print(arr[0,4])

5


In [43]:
print(arr[1,-3])

8


In [44]:
print(arr[1, 1:4])

[7 8 9]


### Mengecek tipe data pada Array

In [46]:
arr = np.array([1,2,3,4])

In [47]:
print(arr.dtype)

int64


In [50]:
arr = np.array([1,2,3,4], dtype='S')

In [51]:
print(arr)

[b'1' b'2' b'3' b'4']


In [52]:
print(arr.dtype)

|S1


In [53]:
arr[0]

b'1'

In [57]:
arr = np.array([1,2,3,4], dtype='I')

In [58]:
print(arr)

[1 2 3 4]


In [59]:
print(arr.dtype)

uint32


In [60]:
arr = np.array([1,2,3,4], dtype=np.int32)

In [61]:
print(arr)

[1 2 3 4]


In [62]:
print(arr.dtype)

int32


### Mengubah tipe data pada Numpy Array

In [64]:
arr = np.array([1.1,2.1,3.1])

In [65]:
print(arr.dtype)

float64


In [66]:
arr = arr.astype('i')

In [67]:
arr

array([1, 2, 3], dtype=int32)

In [68]:
print(arr.dtype)

int32


### Fungsi Arange

In [69]:
arr = np.arange(20)

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
print(type(arr))

<class 'numpy.ndarray'>


In [75]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [74]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [76]:
arr = np.arange(10,20)

In [77]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [78]:
arr = np.arange(10,20,2)

In [79]:
arr

array([10, 12, 14, 16, 18])

In [80]:
arr = np.arange(-1, 1, 0.1)
arr

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])