# Operation

In [1]:
import numpy as np

### Iterasi pada Numpy Array 1D

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
for x in arr:
    print(x)

1
2
3
4
5


### Iterasi pada Numpy Array 2D

In [4]:
arr = np.array([[1,2,3],[4,5,6]])

In [5]:
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


### Iterasi pada Numpy Array 3D

In [6]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [7]:
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


## Array Iterating nditer()

### Iterasi dengan nditer

In [8]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [9]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


## Array Iterating ndenumerate()

In [11]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [14]:
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12
