# Random

In [1]:
from numpy import random

### Mendapatkan nilai integer secara random

In [4]:
x = random.randint(10000)

In [5]:
print(x)

6693


### Mendapatkan nilai float secara random

In [6]:
x = random.rand()

In [7]:
print(x)

0.002929560802255149


### Membuat array 1D dengan nilai integer secara random

In [8]:
x = random.randint(100, size=(5))

In [9]:
print(x)

[69 25 37 99 79]


### Membuat array 2D dengan nilai float secara random

In [11]:
x = random.rand(3, 5)

In [12]:
print(x)

[[0.37258042 0.03157552 0.9867943  0.7604204  0.48579311]
 [0.71956251 0.44485772 0.66817026 0.30495184 0.75228517]
 [0.72113156 0.63052357 0.07189828 0.8064758  0.01004825]]


### Membuat nilai integer random dari Array 1D

In [13]:
x = random.choice([3,5,7,9])

In [14]:
print(x)

3


### Mengacak nilai yang ada pada Array 1D

In [15]:
import numpy as np

In [16]:
arr = np.array([1,2,3,4,5])

In [18]:
random.shuffle(arr)

In [19]:
print(arr)

[2 1 5 4 3]
