# Filter

In [1]:
import numpy as np

### Filter pada numpy Array 1D

In [4]:
arr = np.array([41, 42, 43, 44])

In [5]:
x = [True, False, True, False]

In [6]:
arr = arr[x]

In [7]:
print(arr)

[41 43]


In [8]:
arr = np.array([41, 42, 43, 44])

In [9]:
filter_arr = arr > 42

In [10]:
filter_arr

array([False, False,  True,  True])

In [11]:
arr = arr[filter_arr]

In [12]:
arr

array([43, 44])

In [13]:
arr = np.array([1,2,3,4,5,6,7])

In [14]:
filter_arr = arr & 2 == 0

In [15]:
arr = arr[filter_arr]

In [16]:
arr

array([1, 4, 5])

### Filter pada Numpy Array 1D menggunakan lebih dari 1 kondisi

In [17]:
arr = np.array([1,2,3,4,5,6,7])

In [21]:
filter_arr = (arr % 2 == 0) & (arr > 2)

In [22]:
arr = arr[filter_arr]

In [23]:
arr

array([4, 6])

### Filter pada Numpy Array 2D

In [24]:
arr = np.array([['1', 'one'],
               ['2', 'two'],
               ['3', 'three'],
               ['4', 'four'],
               ['5', 'five']])

In [25]:
arr.shape

(5, 2)

In [26]:
filter_arr = np.array(["two", "four"])

In [27]:
arr = arr[np.in1d(arr[:,1], filter_arr)]

In [28]:
arr

array([['2', 'two'],
       ['4', 'four']], dtype='<U5')